print("Maximiliano Hernández Meza")
print("17 años")
print("Pachuca Hidalgo")
print("Mi comida favorita es el sushi")
print("Mi pelicula favortia es Bladerunner 2049")
print("Mi cancion favorita es Only Be Me --DROLOE")
print("==============================================")
print("1")
print("2")
print("3")
print("4")
print("5")
print("Mis metas como programador serian poder trabajar para una empresa tech reconocida o que apena svaya comenzando,, ganar mucho dinero, y poder hacer IA o bots o algo relacionado a ello")
print()
print("Mi stack favorito por ahora es la IA peor puede que el backend sea lo mejor")
print("No te rindas, auqnue pareza dificl lo que vayas a hacer no significa que sea imposible, todo tiene su dificultad promete que lograrás lo que te prometas")