print("========================================")
print()
print("         PERFIL DEL PROGRAMADOR    ")
print()
print("========================================")
print()
print("Nombre: Max")
print("Edad: 17")
print("Ciudad: Pachuca Hidalgo")
print("Lenguaje: Python")
print("Objetivo: Desarrollador Backend")
print("========================================")
print()
print("========================================")
print()
print("         El codigo es mi herramienta    ")
print()
print("========================================")
